/**
 * THIS FILE IS GENERATED by `gulp env` command from `env.json`
 * Generated on Wed Aug 17 2016 12:12:34 GMT+0300 (FLE Daylight Time)
 *
 * Make sure the keys in `env.model.ts` exist in `env.json`
 * otherwise it'll throw message like this
 * Property '<missing-key>' is missing in type '{}'
 *
 * Feel free to modify for direct updates in development
 */

import {AppEnv} from './template/env.model';

export let Env: AppEnv = <AppEnv>{
    production: false,
    domain: 'localhost',
    url: 'http://localhost:3075',
    api: 'http://api.localhost:8000/v1',
    auth: 'http://localhost:3075/auth',
    dash: 'http://localhost:3075/dash',
    admin: 'http://localhost:3075/admin',
};
