<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php
    echo $this->headTitle('Assessment');

    echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
    ?>
    <!-- CSS -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Bootstrap theme from bootswatch -->
    <link rel="stylesheet" href="https://bootswatch.com/cosmo/bootstrap.min.css">
</head>
<!-- apply our angular app -->
<body ng-app="app">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Assessment</a>
            </div>

            <div class="collapse navbar-collapse" id="navbar">
                <ul class="nav navbar-nav">
                    <li><a href="#/users">Users</a></li>
                    <li><a href="#/bonuses">Bonuses</a></li>
                    <li><a href="#/wallets">Wallets</a></li>
                    <li><a href="#/play">Play</a></li>
                    <li><a href="#/">Login</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <!-- inject our views using ng-view -->
        <div class="page" ng-view></div>
    </div>

    <!-- load angular, ngResource, ngRoute, ngAnimate, ngStorage -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular-resource.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular-route.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular-animate.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ngStorage/0.3.6/ngStorage.min.js"></script>

    <!-- AngularJS app -->
    <script src="js/app.js"></script>
</body>
</html>
